services:
  service:
    container_name: clob_service
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      # This is the debug port for dlv. Must match the value in .air.toml.
      - "4000:4000"
    environment:
      - PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clob_db
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clob_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  postgres_data:
